baseURL = 'https://pugau.ge/'
title = 'Professional Union of Georgian Architects and Urbanists'

defaultContentLanguage = "ka"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  [params.author]
    email = "pugaugeo@gmail.com"
    name = "PUGAU"

[outputs]
  home = ['html']

[languages]
  [languages.en]
        label = "English"
        weight = 2
        title = "PUGAU - Professional Union of Georgian Architects and Urbanists"
        locale = 'en-us'
    [languages.en.params]
          shortLabel = "Eng"
          logoText = "Professional Union of Georgian Architects and Urbanists"
          description = 'Professional union of Georgian architects and urbanists.'

          [[languages.en.menus.main]]
            name = "Main"
            pageref = "/"
            weight = 2
#          [[languages.en.menus.main]]
#            name = "CoC"
#            pageref = "/coc"
#            weight = 3
#          [[languages.en.menus.main]]
#            name = "FAQ"
#            pageref = "/faq"
#            weight = 3
#          [[languages.en.menus.main]]
#            name = "Articles"
#            pageref = "/articles/"
#            weight = 4
          [[languages.en.menus.main]]
            name = "Contact"
            url = "mailto:pugaugeo@gmail.com"
            weight = 5
          [[languages.en.menus.main]]
            name = "Join Us"
            url = "https://docs.google.com/forms/d/e/1FAIpQLSemDONVNK_Kp2iLulc3Q1XuO7idMoXc6qtCrJFX-Z0ociS-hg/viewform"
            weight = 6

  [languages.ka]
        label = "ქართული"
        weight = 1
        title = "PUGAU - საქართველოს არქიტექტორთა და ურბანისტთა პროფესიული კავშირი"
        locale = 'ka'

    [languages.ka.params]
          shortLabel = "ქარ"
          logoText = "საქართველოს არქიტექტორთა და ურბანისტთა პროფესიული კავშირი"
          description = 'საქართველოს არქიტექტორთა და ურბანისტთა პროფესიული კავშირი.'

          [[languages.ka.menus.main]]
            name = "მთავარი"
            pageref = "/"
            weight = 2
#          [[languages.ka.menus.main]]
#            name = "წესდება"
#            pageref = "/coc"
#            weight = 3
#          [[languages.ka.menus.main]]
#            name = "FAQ"
#            pageref = "/faq"
#            weight = 3
#          [[languages.ka.menus.main]]
#            name = "სტატიები"
#            pageref = "/articles/"
#            weight = 4
          [[languages.ka.menus.main]]
            name = "კონტაქტი"
            url = "mailto:pugaugeo@gmail.com"
            weight = 5
          [[languages.ka.menus.main]]
            name = "შემოგვიერთდი"
            url = "https://docs.google.com/forms/d/e/1FAIpQLSemDONVNK_Kp2iLulc3Q1XuO7idMoXc6qtCrJFX-Z0ociS-hg/viewform"
            weight = 6


